services:
  ts-to-mkv:
    image: ghcr.io/rizz360/ts-to-mkv:latest
    pull_policy: always
    # Local development fallback:
    # build: .
    container_name: ts-to-mkv
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /mnt/hjem_nas_dvr/Encode-Queue/:/input
      - /mnt/hjem_nas_media/Movies:/output
    env_file:
      - ./config/.env
    entrypoint: /app/entrypoint.sh
    environment:
      - TZ=Europe/Luxembourg
      - PUID=1000
      - PGID=1000
    # restart: unless-stopped
networks: {}
